### ISSUE TITLE
HTML entities in category names

### ISSUE THREAD

**Issue by seagyn** [staticfuse/staticfuse#47]
I've noticed this in the Footer component with my categories. I have a category `Health & Fitness` and I'm assuming when it's retrieved it's coming back as `Health &amp; Fitness`. 

I've fixed it for me by overriding the Footer component but I'm not sure if anything with a HTML entity will essentially come back "escaped" like titles, menus etc.

I don't want to open a PR as there might be a better fix but thought this would be a good starting point:

```<Link to={item.path} dangerouslySetInnerHTML={{__html: item.context.name}} />```

**Comment by scottopolis** [comment]
Fixed, thanks!
