### ISSUE TITLE
menuName option isn't working as described

### ISSUE THREAD

**Issue by nicolad** [staticfuse/staticfuse#50]
In `README` it says `The name of the WordPress menu you'd like to use or 0 if you don't want to render a menu.`
I've set `menuName` key to `0`, but it still renders the menu.
***
![image](https://user-images.githubusercontent.com/1477453/68071806-e4f1af00-fd86-11e9-9028-53cf16b13903.png)

***
here is the menu being rendered: https://kaizen.blog

**Comment by justinwhall** [comment]
Hey there! So you're looking for a way to have _no menu at all_? What we do is we look for a menu, if you have a WP menu set, we use that. If not, we render the default publisher menu: Home, blog, about, contact. You can see that logic [here](https://github.com/staticfuse/staticfuse/blob/master/packages/gatsby-theme-publisher/src/components/Menu.js#L130). 

I suppose we should also have a check here if you have `starterPages` set to `0`, then render no menu items. Does that help?

**Comment by nicolad** [comment]
Yes, it wouldn't make sense to default to publisher menu when there are no starter pages.

**Comment by nicolad** [comment]
Have created a PR for this: https://github.com/staticfuse/staticfuse/pull/52
